---
- name: Working with JSON data
  hosts: localhost
  become: yes
  tasks:
    - name: Download JSON data
      uri:
        url: https://jsonplaceholder.typicode.com/users
        remote_content: yes
      register: jsoncontent

    - name: Get User Name
      debug: msg="{{ jsoncontent.json | json_query(username) }}"
      vars:
        username: "[*].name"