---
-   hosts: all
    become: true
    tasks:
        -   name: Instaling Apache2
            apt:
                name: 
                -  apache2
                state: absent
        # -   service: name=apache2 state=started enabled=yes       
        # -   raw: "echo Welcome to HTTPD Ansible Project | sudo tee /var/www/html/index.html"