---
- name: "Install and Lanuch the simple nodejs application"
  hosts: PRD
  become: yes
  vars_files:
    - secret.yaml
  vars: 
    - destdir: /apps/SampleNodejsApp
  tasks:
    - name: Update Distribution
      shell: "sudo apt-get update"
    - name: Download and Install nodejs and NPM
      become: yes
      register: installnodejs
      apt:
        name: 
        - nodejs
        - npm
        state: latest
    - name: Validate the nodejs installation
      debug: msg="Installation of nodejs is Successfull"
      when: installnodejs is changed
    - name: Version of Node and NPM
      shell:
        "npm -v && node -v"
      register: versioninfo
    - name: Version Info
      debug: msg="{{ versioninfo.stdout_lines }}"
      when: versioninfo is changed
    - name: Download the NodeJS code from the GitRepo
      git:
        repo: 'https://{{gituser}}:{{gitpass}}@github.com/sunilc18/sampleproject-nodejs-ansible.git'
        dest: "{{ destdir }}"
    - name: Change the Directory ownership
      file:
        path: "{{ destdir }}"
        owner: "vagrant"
      register: chgrpout
    - name: Install Dependencies with NPM install command
      shell:
        "npm install"
      args:
        chdir: "{{ destdir }}"
      register: npminstlout
    - name: Debug npm install command
      debug: msg="{{ npminstlout.stdout_lines }}"
    - name: Start the App
      async: 10
      poll: 0
      shell:
        "( node index.js > nodesrv.log 2>&1 & )"
      args:
        chdir: "{{ destdir }}"
      register: appstart
    - name: Validate the port is open
      tags: nodevalidate
      wait_for:
        host: "localhost"
        port: 5000
        delay: 10
        timeout: 30
        state: started
        msg: "NodeJ server is not running"
