---
- name: Example02 of Firewalld module
  hosts: node1
  become: yes
  tasks:
    - name: Enabling and Disabling of Ports
      firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        state: "{{item.state}}"
        zone: "{{item.zone}}"
      with_items:
        - {port: "8080", proto: "tcp", state: "disabled", zone: "public"}
        - {port: "161-162", proto: "udp", state: "disabled", zone: "internal"}
        - {port: "9001", proto: "tcp", state: "enabled", zone: "public"}