---
- name: Example04 of Firewalld module
  hosts: node1
  become: yes
  tasks:
    - name: Port Forwarding
      firewalld:
        permanent: yes
        immediate: yes
        rich_rule: "{{item}}"
        state: enabled
      with_items:
        - 'rule forward-port port=80 protocol=tcp to-port=8080 family=ipv4'
