---
- name: AWS S3 Bucket list - Ansible
  hosts: localhost
  tasks:
    - name: List keys or objects
      aws_s3:
        # profile: <name> # configured on our localmachine with AWS CLI. In my case i used export cmd.
        bucket: sunilcbucket
        mode: list
        max_keys: 1
        prefix: "test1/test1-subfolder/" # from folder or subfolder
        marker: "test1/test1-subfolder/test3.txt"  # from which file it should start the listing if files
      register: listresult

    - debug: msg="{{listresult.s3_keys}}"