---
- name: Ansible APT module
  hosts: node1
  become: yes
  tasks:
    - name: Install FileBeat using DEB file
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.15.1-amd64.deb
      register: installfilebeat
    
    - debug: msg="{{installfilebeat}}"