---
- name: Example08 of wait_for module
  hosts: node1
  become: yes
  tasks:
    - name: Patch the server
      become_user: vagrant
      tags: patch
      shell: "sudo apt -y update"
      register: patchresult

    - name: Reboot the server
      tags: reboot
      become_user: vagrant
      shell: "sleep 5 & reboot"
      async: 5
      poll: 0

    - name: Wait for the reboot and reconnect the host
      wait_for:
        port: 22
        host: "{{ansible_hostname}}"
        search_regex: OpenSSH
        delay: 30
        timeout: 60
      connection: local

    - name: Check the Uptime of the server
      shell: "uptime"
      register: uptime
    
    - debug: var=uptime

