---
- name: Create EC2 Instances
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Get Running instance Info
      ec2_instance_facts:
        region: us-east-2
      register: ec2info 

    - name: Print info
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2info.instances}}"

    - name: Terminate instance
      ec2:
        instance_ids: "{{ item.instance_id }}"
        region: us-east-2
        state: absent
        wait: yes
      with_items: "{{ ec2info.instances }}"
             

    