---
- name: Creation of EC2 instance
  hosts: localhost
  tasks:
    - name: Launch ec2 instances
      ec2:
        region: us-east-2
        key_name: new_aws
        instance_type: t2.micro
        image: ami-07b1d7739c91ed3fc
        wait: yes
        wait_timeout: 500
        count: 2
        instance_tags:
          name: appservers
          os: ubuntu
        monitoring: no
      register: ec2
      delegate_to: localhost

    # - name: Get info
    #   ec2_instance_facts: 
    #     region: us-east-2
    #   register: ec2
    
    # - name: Print Info
    #   debug: msg="{{ item.instance_id }}"
    #   with_items: "{{ ec2.instances }}"