---
- name: Complete EC2 creation project
  hosts: localhost
  # vars_files:
  #   - secret.yaml
  gather_facts: false
  tasks:
    - name: Get Info block
      block:
        - name: Get Running instances info
          ec2_instance_facts:
            region: us-east-2
          register: ec2info
        
        - name: Print info
          debug: var="ec2info.instances"

      tags: ['always', 'getinfoonly']

    - name: Create EC2 Block
      block:
        - name: Launch EC2 instances
          tags: create_ec2
          ec2:
            region: us-east-2
            key_name: new_aws
            instance_type: t2.micro
            image: ami-07b1d7739c91ed3fc
            wait: yes
            wait_timeout: 500
            count: 2
            instance_tags:
              name: appservers
              os: ubuntu
          register: ec2
          delegate_to: localhost

        - name: Add instance to host group
          add_host:
            hostname: "{{ item.public_ip }}"
            groupname: launched
          loop: "{{ ec2.instances }}"

        - name: Wait for SSH to come up
          local_action:
            module: wait_for
            host: "{{ item.public_ip }}"
            port: 22
            delay: 10
            timeout: 120
          loop: "{{ ec2.instances }}"

      tags: ['never', 'ec2-create']

